version: '3.8'

networks:
  front:
    driver: bridge
  back:
    driver: bridge

services:
  api:
    build:
      context: ./dock/php
    restart: always
    tty: true
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_MEMORY_LIMIT: "1G"
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_PDO_ODBC: 1
      PHP_EXTENSION_APCU: 1
      PHP_EXTENSION_OPCACHE: 1
      PHP_EXTENSION_PDO: 1
      PHP_EXTENSION_REDIS: 1
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG}"
      XDEBUG_CONFIG: "remote_host=${REMOTE_HOST} remote_enable=1"
    volumes:
      - $PWD/app:/var/www/html
    networks:
      - back
    working_dir: /var/www/html

  nginx:
    build:
      context: ./dock/nginx
    working_dir: /var/www/html
    depends_on:
      - api
    volumes:
#      - $PWD/vue:/var/www/vue
      - $PWD/app:/var/www/html
    networks:
#      - front
      - back
    ports:
#    - "${FRONT_PORT}:80"
    - 8080:8080

  postgres:
    image: "postgres:12.4"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - $PWD/dock/volumes/db:/var/lib/postgresql/data
    networks:
      - back
    ports:
      - ${PORT_DB}:5432

# Nuxt
  vue:
    build:
      context: ./dock/vue
    tty: true
    user: "${UID}:${GID}"
    volumes:
    - $PWD/vue:/var/www/vue
    working_dir: /var/www/vue
    environment:
      - HOST=0.0.0.0
    ports:
      - "80:3000"
    networks:
      - front
    depends_on:
      - json-server

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]

  json-server:
    build:
      context: ./dock/json-server
    volumes:
    - $PWD/json-server:/var/www/json-server
    user: "${UID}:${GID}"
    tty: true
    working_dir: /var/www/json-server
    ports:
    - "3004:3004"
    restart: always
    networks:
      - front